const CONFIG = { brandName: "Paseos Lua", whatsappNumber: "5491151512248", serviceArea: "Almagro · Caballito · Balvanera" };

const questions = [
  { id:"name", category:"sobre tu perro", title:"¿Cómo se llama tu perro?", type:"text", placeholder:"Su nombre" },
  { id:"age", category:"sobre tu perro", title:"¿Qué edad tiene?", options:[ ["puppy","🐶","Menos de 1 año","Cachorro"], ["young","🌱","1 a 3 años","Joven"], ["adult","🐕","4 a 7 años","Adulto"], ["senior","🌿","8 a 11 años","Adulto mayor / senior"], ["elder","🤎","12 años o más","Senior"] ] },
  { id:"energy", category:"su personalidad", title:"Si tuvieras que describir su energía, ¿cuál se parece más?", options:[ ["calm","😌","Tranquilo/a","Disfruta salir, pero no necesita estar en movimiento todo el tiempo."], ["active","🌿","Activo/a","Le gusta caminar, explorar y mantenerse en movimiento."], ["veryActive","⚡","Muy activo/a","Tiene mucha energía y suele necesitar bastante actividad."] ] },
  { id:"dogs", category:"cómo se relaciona", title:"¿Cómo suele relacionarse con otros perros?", options:[ ["loves","🐕💕","Le encantan","Busca acercarse y suele disfrutar mucho de estar con ellos."], ["fine","🐾","Se lleva bien","Puede compartir un paseo tranquilamente."], ["distance","🌿","Prefiere cierta distancia","Está bien con otros, pero no busca demasiado contacto."], ["struggles","👀","Le cuesta","Puede ponerse nervioso, ladrar, tirar o reaccionar."], ["strong","🚨","Tiene reacciones fuertes","Puede representar una dificultad importante durante el paseo."] ] },
  { id:"people", category:"cómo se relaciona", title:"¿Y con las personas que no conoce?", options:[ ["social","🥰","Es muy sociable","Se acerca con confianza y disfruta el contacto."], ["friendly","🙂","Es amigable, pero tranquilo/a","Se relaciona bien sin buscar demasiado."], ["observes","👀","Primero observa","Necesita un poco de tiempo para entrar en confianza."], ["reserved","🌿","Es bastante reservado/a","Prefiere mantener cierta distancia."], ["reactive","🚨","Puede reaccionar o ponerse nervioso/a","Las personas nuevas pueden resultarle difíciles."] ] },
  { id:"walk", category:"durante el paseo", title:"Durante un paseo, ¿qué suele hacer más?", options:[ ["explores","🐽","Se detiene a olfatear y explorar todo",""] , ["moves","🏃","Quiere avanzar y moverse",""] , ["dogsFocus","🐕","Está muy pendiente de otros perros",""] , ["alert","👀","Está atento/a a todo lo que pasa alrededor",""] , ["steady","😌","Camina tranquilo/a y sigue su recorrido",""] ] },
  { id:"experience", category:"experiencia", title:"¿Qué experiencia tiene saliendo a pasear?", options:[ ["regular","🐾","Sale habitualmente","Está acostumbrado/a a pasear."], ["sometimes","🙂","Sale de vez en cuando","Tiene algo de experiencia."], ["rarely","🌱","Casi nunca sale","Los paseos no forman parte de su rutina."], ["never","🏠","Nunca salió a pasear","Sería su primera experiencia."], ["otherPerson","✨","Nunca salió con otra persona","Sale con su cuidador, pero no está acostumbrado/a a hacerlo con alguien más."] ] },
  { id:"preference", category:"sus preferencias", title:"¿Qué tipo de paseo creés que disfrutaría más?", options:[ ["explore","🌿","Explorar y olfatear",""] , ["move","🏃","Caminar y moverse",""] , ["social","🐕","Compartir con otros perros",""] , ["routine","😌","Salir tranquilo/a y mantener una rutina",""] , ["mixed","🎾","Un poco de todo",""] ] },
  { id:"frequency", category:"su rutina", title:"¿Cuántos paseos por semana te gustaría que tuviera?", helper:"Elegí la frecuencia que más se parezca a la rutina que querés para él.", options:[ [1,"🐾","1 paseo",""], [3,"🌱","3 paseos",""], [5,"🐕","5 paseos",""], [6,"✨","6 paseos",""], [7,"🌿","7 paseos",""], [10,"⚡","10 paseos",""], [14,"💚","14 paseos",""] ] }
];

let step = 0; const answers = {}; const app = document.querySelector("#app");
const shell = (content, kind="") => `<div class="shell ${kind}"><header class="brand"><i class="moon"></i>${CONFIG.brandName}</header>${content}</div>`;
function landing() { app.innerHTML = shell(`<section class="hero"><div class="eyebrow">${CONFIG.serviceArea}</div><h1>¿Qué paseo va mejor con tu perro?</h1><p>Respondé unas preguntas sobre su energía, su forma de relacionarse y lo que disfruta. Al final, Lua te va a recomendar una rutina pensada para él.</p><button class="primary" id="start">Conocer su perfil →</button></section><footer class="area">Paseos pensados para cada perro.</footer>`, "landing"); document.querySelector("#start").onclick = renderQuestion; }
function renderQuestion() { const q=questions[step], selected=answers[q.id]; const body=q.type === "text" ? `<input class="name-input" id="answer" maxlength="40" autocomplete="off" placeholder="${q.placeholder}" value="${selected || ""}">` : `<div class="options">${q.options.map(([value,icon,label,detail])=>`<button type="button" class="option ${String(selected)===String(value)?"selected":""}" data-value="${value}"><span class="option-icon">${icon}</span><span><strong>${label}</strong>${detail?`<small>${detail}</small>`:""}</span></button>`).join("")}</div>`; app.innerHTML=shell(`<div class="quiz-header"><span class="progress-text">${String(step+1).padStart(2,"0")} / ${String(questions.length).padStart(2,"0")}</span><span class="category">${q.category}</span></div><div class="progress"><span style="width:${((step+1)/questions.length)*100}%"></span></div><section class="question"><h1 class="question-title">${q.title}</h1>${q.helper?`<p class="helper">${q.helper}</p>`:""}${body}<p class="error" id="error"></p></section><nav class="nav"><button class="secondary" id="back" ${step===0?"hidden":""}>← Atrás</button><button class="primary" id="next">${step===questions.length-1?"Ver recomendación →":"Siguiente →"}</button></nav>`); if(q.type==="text") document.querySelector("#answer").focus(); document.querySelectorAll(".option").forEach(el=>el.onclick=()=>{ answers[q.id]=q.id==="frequency"?Number(el.dataset.value):el.dataset.value; renderQuestion(); }); document.querySelector("#back").onclick=()=>{ step--; renderQuestion(); }; document.querySelector("#next").onclick=next; }
function next() { const q=questions[step]; if(q.type==="text") answers[q.id]=document.querySelector("#answer").value.trim(); if(!answers[q.id]) { document.querySelector("#error").textContent=q.type==="text"?"Escribí el nombre de tu perro para continuar.":"Elegí una opción para continuar."; return; } if(step===questions.length-1) renderResult(); else { step++; renderQuestion(); } }
function calculateProfile(a) { const age={puppy:8,young:2,adult:0,senior:-13,elder:-22}[a.age]; const energy={calm:28,active:63,veryActive:88}[a.energy]+age; const sociability={loves:92,fine:72,distance:45,struggles:24,strong:8}[a.dogs]; const exploration=clamp(({explores:90,moves:62,dogsFocus:50,alert:45,steady:32}[a.walk] + {explore:12,move:5,social:2,routine:-8,mixed:6}[a.preference])); const sensitivity=clamp(({social:18,friendly:30,observes:55,reserved:68,reactive:88}[a.people] + {alert:10,steady:-8,explores:-5,moves:-2,dogsFocus:5}[a.walk])); const adaptability=clamp(({regular:85,sometimes:65,rarely:45,never:28,otherPerson:40}[a.experience] + {puppy:4,young:5,adult:2,senior:-6,elder:-11}[a.age])); return { energy:clamp(energy), sociability, exploration, sensitivity, adaptability }; }
function clamp(n) { return Math.max(0,Math.min(100,Math.round(n))); }
function recommendModality(a, p) { if(a.dogs==="strong" || a.people==="reactive") return { name:"Individual", reason:"Por cómo se relaciona con perros o personas nuevas, un paseo individual permite respetar mejor sus tiempos y acompañarlo con atención personalizada." }; if(a.dogs==="struggles" || a.dogs==="distance" || a.people==="reserved") return { name:"Individual", reason:"Le puede venir bien una salida individual, tranquila y adaptable a su ritmo mientras gana confianza en el entorno." }; if(a.dogs==="loves" || (a.dogs==="fine" && a.preference==="social")) return { name:"Grupal", reason:"Su vínculo con otros perros sugiere que puede disfrutar un paseo grupal cuidadosamente armado y con compañeros compatibles." }; return { name:"Individual", reason:"Para su perfil, empezar con una modalidad individual permite conocer mejor su ritmo y ajustar cada salida a lo que necesita." }; }
function recommendDuration(a,p) { if(a.age==="elder") return "30 minutos"; if(a.age==="senior") return p.energy>=60?"45 minutos":"30 minutos"; if(p.energy>=78) return "60 minutos"; if(p.energy>=48) return "45 minutos"; return "30 minutos"; }
function renderResult() { const profile=calculateProfile(answers), modality=recommendModality(answers,profile), duration=recommendDuration(answers,profile), name=answers.name; const labels={energy:"Energía",sociability:"Sociabilidad",exploration:"Exploración",sensitivity:"Sensibilidad",adaptability:"Adaptación"}; const message=`Hola!\nCompleté el cuestionario para ${name} y quiero consultar disponibilidad.\n\n🐾 Resumen de ${name}\n• Edad: ${questions[1].options.find(x=>x[0]===answers.age)[2]}\n• Paseos por semana: ${answers.frequency}\n• Modalidad recomendada: ${modality.name}\n• Duración recomendada: ${duration}\n\n📊 Perfil\n• Energía: ${profile.energy}%\n• Sociabilidad: ${profile.sociability}%\n• Exploración: ${profile.exploration}%\n• Sensibilidad: ${profile.sensitivity}%\n• Adaptación: ${profile.adaptability}%`; const url=`https://wa.me/${CONFIG.whatsappNumber}?text=${encodeURIComponent(message)}`; app.innerHTML=shell(`<section class="result"><div class="eyebrow">Perfil de ${name}</div><h1 class="result-title">Un paseo pensado para ${name}.</h1><p class="result-intro">Esta primera recomendación combina su energía, su forma de relacionarse y su experiencia. Siempre la ajustamos con una primera charla.</p><div class="recommendation"><article class="rec-card"><span>Modalidad</span><strong>${modality.name}</strong></article><article class="rec-card"><span>Duración</span><strong>${duration}</strong></article><article class="rec-card"><span>Frecuencia elegida</span><strong>${answers.frequency} ${answers.frequency===1?"paseo":"paseos"}</strong></article></div><div class="reason">${modality.reason}</div><div class="profile"><h2>Su perfil</h2>${Object.entries(profile).map(([key,value])=>`<div class="dimension"><span>${labels[key]}</span><div class="meter"><span style="width:${value}%"></span></div><strong>${value}%</strong></div>`).join("")}</div><a class="primary whatsapp" href="${url}" target="_blank" rel="noopener">Consultar por WhatsApp →</a><button class="secondary" id="restart">← Volver a empezar</button></section>`); document.querySelector("#restart").onclick=()=>{step=0; Object.keys(answers).forEach(k=>delete answers[k]); landing();}; }
landing();
