/* Datos comerciales y de cuestionario */
const CONFIG = { brandName: "Paseos Lua", whatsappNumber: "5491151512248", serviceArea: "Almagro · Caballito · Balvanera" };
const DELTAS = {
  age:{ puppy:{energy:10,adaptability:-5}, young:{}, adult:{}, senior:{energy:-8,sensitivity:5}, elder:{energy:-15,sensitivity:10} },
  energy:{ calm:{energy:-20,adaptability:5}, active:{energy:10,exploration:5}, high:{energy:30,exploration:10} },
  dogs:{ loves:{sociability:35,adaptability:10}, good:{sociability:20,adaptability:5}, distance:{sociability:-5}, struggles:{sociability:-20,sensitivity:15,adaptability:-10}, strong:{sociability:-40,sensitivity:30,adaptability:-25} },
  people:{ social:{adaptability:15,sensitivity:-10}, friendly:{adaptability:10}, observes:{sensitivity:5}, reserved:{sensitivity:10,adaptability:-5}, reacts:{sensitivity:25,adaptability:-20} },
  walk:{ explore:{exploration:30}, move:{energy:15,exploration:10}, dogs:{sociability:5,sensitivity:10}, alert:{sensitivity:15}, calm:{adaptability:15,energy:-5} },
  difficulties:{ pull:{energy:5,adaptability:-10}, distracted:{adaptability:-10}, noises:{sensitivity:25,adaptability:-15}, dogReact:{sensitivity:25,sociability:-20,adaptability:-20}, peopleReact:{sensitivity:20,adaptability:-15}, unsettled:{energy:10,adaptability:-15}, none:{} },
  experience:{ regular:{adaptability:10}, sometimes:{adaptability:2}, rarely:{adaptability:-8}, never:{adaptability:-10}, otherPerson:{adaptability:-5} },
  preference:{ explore:{exploration:15}, move:{energy:15}, dogs:{sociability:20}, calm:{adaptability:10,energy:-5}, mix:{energy:5,exploration:5,sociability:5,adaptability:5} }
};
const QUESTIONS = [
  {id:'name',category:'sobre tu perro',title:'¿Cómo se llama tu perro?',type:'text'},
  {id:'age',category:'sobre tu perro',title:'¿Qué edad tiene?',options:[['puppy','🐶 Menos de 1 año','Cachorro'],['young','🌱 1 a 3 años','Joven'],['adult','🐕 4 a 7 años','Adulto'],['senior','🌿 8 a 11 años','Adulto mayor / senior'],['elder','🤎 12 años o más','Senior']]},
  {id:'energy',category:'su personalidad',title:'Si tuvieras que describir su energía, ¿cuál se parece más?',options:[['calm','😌 Tranquilo/a','Disfruta salir, pero no necesita estar en movimiento todo el tiempo.'],['active','🌿 Activo/a','Le gusta caminar, explorar y mantenerse en movimiento.'],['high','⚡ Muy activo/a','Tiene mucha energía y suele necesitar bastante actividad.']]},
  {id:'dogs',category:'cómo se relaciona',title:'¿Cómo suele relacionarse con otros perros?',options:[['loves','🐕💕 Le encantan','Busca acercarse y suele disfrutar mucho de estar con ellos.'],['good','🐾 Se lleva bien','Puede compartir un paseo tranquilamente.'],['distance','🌿 Prefiere cierta distancia','Está bien con otros, pero no busca demasiado contacto.'],['struggles','👀 Le cuesta','Puede ponerse nervioso, ladrar, tirar o reaccionar.'],['strong','🚨 Tiene reacciones fuertes','Puede representar una dificultad importante durante el paseo.']]},
  {id:'people',category:'cómo se relaciona',title:'¿Y con las personas que no conoce?',options:[['social','🥰 Es muy sociable','Se acerca con confianza y disfruta el contacto.'],['friendly','🙂 Es amigable, pero tranquilo/a','Se relaciona bien sin buscar demasiado.'],['observes','👀 Primero observa','Necesita un poco de tiempo para entrar en confianza.'],['reserved','🌿 Es bastante reservado/a','Prefiere mantener cierta distancia.'],['reacts','🚨 Puede reaccionar o ponerse nervioso/a','Las personas nuevas pueden resultarle difíciles.']]},
  {id:'walk',category:'durante el paseo',title:'Durante un paseo, ¿qué suele hacer más?',options:[['explore','🐽 Se detiene a olfatear y explorar todo'],['move','🏃 Quiere avanzar y moverse'],['dogs','🐕 Está muy pendiente de otros perros'],['alert','👀 Está atento/a a todo lo que pasa alrededor'],['calm','😌 Camina tranquilo/a y sigue su recorrido']]},
  {id:'difficulties',category:'durante el paseo',title:'¿Hay algo que suela costarle durante los paseos?',helper:'Podés elegir más de una.',multi:true,options:[['pull','↔️ Tirar de la correa'],['distracted','🌀 Distraerse constantemente'],['noises','🔊 Asustarse con ruidos o movimiento'],['dogReact','🐕 Reaccionar ante otros perros'],['peopleReact','👤 Reaccionar ante personas'],['unsettled','⏸️ Le cuesta quedarse tranquilo/a'],['none','✓ Nada en particular']]},
  {id:'experience',category:'experiencia',title:'¿Qué experiencia tiene saliendo a pasear?',options:[['regular','🐾 Sale habitualmente','Está acostumbrado/a a pasear.'],['sometimes','🙂 Sale de vez en cuando','Tiene algo de experiencia.'],['rarely','🌱 Casi nunca sale','Los paseos no forman parte de su rutina.'],['never','🏠 Nunca salió a pasear','Sería su primera experiencia.'],['otherPerson','✨ Nunca salió con otra persona','Sale con su cuidador, pero no está acostumbrado/a a hacerlo con alguien más.']]},
  {id:'preference',category:'sus preferencias',title:'¿Qué tipo de paseo creés que disfrutaría más?',options:[['explore','🌿 Explorar y olfatear'],['move','🏃 Caminar y moverse'],['dogs','🐕 Compartir con otros perros'],['calm','😌 Salir tranquilo/a y mantener una rutina'],['mix','🎾 Un poco de todo']]},
  {id:'frequency',category:'su rutina',title:'¿Cuántos paseos por semana te gustaría que tuviera?',helper:'Elegí la frecuencia que más se parezca a la rutina que querés para él.',options:[[1,'🐾 1 paseo'],[3,'🌱 3 paseos'],[5,'🐕 5 paseos'],[6,'✨ 6 paseos'],[7,'🌿 7 paseos'],[10,'⚡ 10 paseos'],[14,'💚 14 paseos']]}
];

/* Lógica reproducible de perfil y recomendación */
const clamp=(n,min=0,max=100)=>Math.max(min,Math.min(max,n));
function add(target,delta={}) { Object.entries(delta).forEach(([key,value])=>target[key]+=value); }
function buildProfile(answers) { const p={energy:50,sociability:50,exploration:50,sensitivity:50,adaptability:50}; ['age','energy','dogs','people','walk','experience','preference'].forEach(id=>add(p,DELTAS[id][answers[id]])); (answers.difficulties||[]).forEach(id=>add(p,DELTAS.difficulties[id])); Object.keys(p).forEach(k=>p[k]=clamp(p[k])); return p; }
function recommendation(answers, p=buildProfile(answers)) {
  const diff=answers.difficulties||[], relevant=diff.filter(x=>x!=='none'), reactiveDogs=diff.includes('dogReact');
  const strongIndividual=answers.dogs==='strong' || (reactiveDogs&&(p.sensitivity>=70||p.adaptability<=45||relevant.length>=2)) || (p.sensitivity>=75&&p.adaptability<=40&&relevant.length>0);
  const modality=!strongIndividual && p.sociability>=65 && p.sensitivity<70 && p.adaptability>=45 ? 'grupal' : 'individual';
  const f=Number(answers.frequency); const senior=['senior','elder'].includes(answers.age);
  let duration=45;
  if (f>=10 || p.energy<45 || p.sensitivity>=70 || p.adaptability<45) duration=30;
  else if (p.energy>=75 && p.sensitivity<60 && p.adaptability>=60 && f<=7) duration=60;
  if (f===10 && duration===30 && p.energy>=75 && p.sensitivity<60 && p.adaptability>=60) duration=45;
  if ((f===1||f===3) && duration===30 && p.energy>=45 && p.sensitivity<70 && p.adaptability>=45) duration=45;
  if (senior && duration===60 && !(p.energy>=85&&p.adaptability>=75&&p.sensitivity<50&&f<=3)) duration=45;
  if (f===14) duration=30;
  return {modality,duration,frequency:f};
}
function makeWhatsAppLink(name) { return `https://wa.me/${CONFIG.whatsappNumber}?text=${encodeURIComponent(`Hola!\nCompleté el cuestionario para ${name} y quiero consultar disponibilidad.`)}`; }
function explanation(name,p,r) { if(r.modality==='individual') return `${name} podría beneficiarse de un paseo más individualizado, con un ritmo adaptado a sus necesidades${p.sensitivity>=70?' y a los estímulos que encuentra durante la salida.':'.'}`; if(p.exploration>=75) return `${name} parece tener una buena predisposición para compartir sus paseos y disfrutar especialmente de explorar. ${r.duration} minutos pueden darle un equilibrio cuidado entre movimiento y olfateo.`; return `${name} parece tener una buena predisposición para compartir sus paseos con otros perros. Una salida de ${r.duration} minutos puede acompañar muy bien su energía y su rutina.`; }
function traits(p) { const values=[['Sociable',p.sociability,'Tiene buena predisposición para compartir el paseo.'],['Explorador/a',p.exploration,'Disfruta recorrer, olfatear y conocer su entorno.'],['Activo/a',p.energy,'Parece beneficiarse de un paseo con movimiento.'],['Sensible',p.sensitivity,'Agradece un ritmo atento a los estímulos.'],['Adaptable',p.adaptability,'Se ajusta bien a nuevas rutinas.']]; return values.sort((a,b)=>b[1]-a[1]).slice(0,3); }

/* Interfaz */
const state={view:'landing',index:0,answers:{}}; const app=document.querySelector('#app');
const brand=()=>`<header class="site-header shell"><div class="brand"><i class="moon" aria-hidden="true"></i><span><strong>${CONFIG.brandName}</strong>Paseos pensados para cada perro.</span></div></header>`;
function render() { if(state.view==='landing') return renderLanding(); if(state.view==='quiz') return renderQuiz(); return renderResult(); }
function renderLanding(){ app.innerHTML=`<section class="landing">${brand()}<div class="hero shell"><div class="hero-copy"><div class="eyebrow">${CONFIG.serviceArea}</div><h1>¿Qué paseo va mejor con tu perro?</h1><p>Respondé unas preguntas sobre su energía, su forma de relacionarse y lo que disfruta. Al final, Lua te va a recomendar una rutina pensada para él.</p><button class="primary" id="start">Conocer su perfil →</button></div><div class="area-note">Zona de paseos · entorno Parque Rivadavia</div></div></section>`; document.querySelector('#start').onclick=()=>{state.view='quiz';render();}; }
function renderQuiz(){ const q=QUESTIONS[state.index], answer=state.answers[q.id]; let choices=''; if(q.type==='text') choices=`<input class="name-field" id="answer-text" placeholder="Su nombre" value="${answer||''}" autocomplete="off" />`; else choices=`<div class="options">${q.options.map(([value,label,detail])=>`<button class="option ${(q.multi?(answer||[]).includes(String(value)):String(answer)===String(value))?'selected':''}" data-value="${value}"><strong>${label}</strong>${detail?`<small>${detail}</small>`:''}</button>`).join('')}</div>`; app.innerHTML=`<section class="quiz-wrap">${brand()}<div class="quiz-card shell"><div class="progress-meta"><span>${String(state.index+1).padStart(2,'0')} / 10</span><span>${q.category.toUpperCase()}</span></div><div class="progress"><span style="width:${(state.index+1)*10}%"></span></div><div class="question-panel"><div class="category">${q.category}</div><h1 class="question-title">${q.title}</h1>${q.helper?`<p class="helper">${q.helper}</p>`:''}${choices}<p id="validation" class="validation"></p></div><div class="quiz-nav"><button class="back" id="back" ${state.index===0?'disabled':''}>← Atrás</button><button class="primary" id="next">${state.index===9?'Ver recomendación →':'Siguiente →'}</button></div></div></section>`;
  if(q.type==='text') document.querySelector('#answer-text').oninput=e=>state.answers.name=e.target.value;
  document.querySelectorAll('.option').forEach(b=>b.onclick=()=>selectOption(q,String(b.dataset.value)));
  document.querySelector('#back').onclick=()=>{state.index--;render();}; document.querySelector('#next').onclick=next;
}
function selectOption(q,value){ if(q.multi){ let selected=state.answers[q.id]||[]; selected=value==='none'?['none']:(selected.filter(x=>x!=='none').includes(value)?selected.filter(x=>x!==value):[...selected.filter(x=>x!=='none'),value]); state.answers[q.id]=selected; } else state.answers[q.id]=q.id==='frequency'?Number(value):value; document.querySelector('#validation').textContent=''; renderQuiz(); }
function next(){ const q=QUESTIONS[state.index],value=state.answers[q.id],valid=q.type==='text'?String(value||'').trim():(q.multi?value&&value.length:Boolean(value||value===0)); if(!valid){document.querySelector('#validation').textContent=q.type==='text'?'Escribí el nombre de tu perro para continuar.':'Elegí una opción para continuar.'; return;} if(state.index===9){state.view='result';render();} else {state.index++;render();} }
function renderResult(){ const p=buildProfile(state.answers),r=recommendation(state.answers,p),name=state.answers.name.trim(), labels={energy:'Energía',sociability:'Sociabilidad',exploration:'Exploración',sensitivity:'Sensibilidad',adaptability:'Adaptación'}; app.innerHTML=`<section class="result-wrap">${brand()}<article class="result-card shell"><div class="eyebrow">Perfil de ${name}</div><h1 class="result-title">Tenemos una idea para ${name}.</h1><p class="result-intro">Tomamos sus respuestas como punto de partida para pensar una rutina que combine su forma de ser con lo que buscás para sus paseos.</p><div class="bars">${Object.entries(labels).map(([k,l])=>`<div><div class="bar-label"><span>${l}</span><span>${p[k]}%</span></div><div class="bar-track"><div class="bar-fill ${k==='sensitivity'?'sensitivity':''}" style="width:${p[k]}%"></div></div></div>`).join('')}</div><section class="recommendation"><div class="eyebrow">La recomendación de Lua</div><h3>Paseo ${r.modality}<br>${r.duration} minutos</h3><p>${r.frequency} ${r.frequency===1?'paseo':'paseos'} por semana</p></section><p class="explanation">${explanation(name,p,r)}</p><div class="traits">${traits(p).map(t=>`<div class="trait"><strong>${t[0]}</strong><span>${t[2]}</span></div>`).join('')}</div><div class="result-actions"><a class="primary whatsapp" href="${makeWhatsAppLink(name)}" target="_blank" rel="noopener">Consultar por WhatsApp →</a><button class="secondary" id="reset">Hacer el cuestionario de nuevo</button></div></article></section>`; document.querySelector('#reset').onclick=()=>{state.view='landing';state.index=0;state.answers={};render();}; }
window.PaseosLua={CONFIG,QUESTIONS,buildProfile,recommendation,makeWhatsAppLink,state}; render();
